/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_time_foundation_include_h__
#define _mulle_objc_time_foundation_include_h__

// You can tweak the following #include with these commands.
// (Use C5642466-3526-461D-A4BD-492BCA6FF633 instead of mulle-time if there are duplicate entries)
//    remove:             `mulle-sde dependency mark mulle-time no-header`
//    rename:             `mulle-sde dependency|library set mulle-time include whatever.h`
//    reorder:            `mulle-sde dependency move mulle-time <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-time [no-]import`
//    toggle public:      `mulle-sde dependency mark mulle-time [no-]public`
//    toggle optional:    `mulle-sde dependency mark mulle-time [no-]require`
//    remove for platform:`mulle-sde dependency mark mulle-time no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-time/mulle-time.h>   // mulle-time

#endif
