      { @selector( NSDate), @selector( NSCoder) },      // cfcedd21;NSDate;100c54ba;NSCoder
      { @selector( NSDate), MULLE_OBJC_NO_CATEGORYID },      // cfcedd21;NSDate;;
      { @selector( NSObject), @selector( _NSDate) },      // b3a66256;NSObject;bf24985e;_NSDate
      { @selector( NSThread), @selector( NSDate) },      // c81b9c22;NSThread;cfcedd21;NSDate
      { @selector( NSTimer), @selector( NSDate) },      // 37c6e578;NSTimer;cfcedd21;NSDate
      { @selector( NSTimer), MULLE_OBJC_NO_CATEGORYID },      // 37c6e578;NSTimer;;
      { @selector( _MulleObjCConcreteDate), MULLE_OBJC_NO_CATEGORYID },      // 59719ae3;_MulleObjCConcreteDate;;
